# This is the set of samples / pairs that we'll process
samples:   

  # Format is TumorPath, NormalPath, TumorPurity, DesiredCoverage
  mixset001:  [/fh/scratch/delete90/ha_g/CRPC_cfDNA/cfDNA_simulated_mixtures/samples/MBC288recal/1.5X/MBC288_1.5Xcover.bam, /fh/scratch/delete90/ha_g/CRPC_cfDNA/cfDNA_simulated_mixtures/samples/HD2recal/1.5X/HD2_1.5Xcover.bam, 0.7600, 0.30]

# This is the tumor fraction set, applied to all samples listed above
fractions: 

  # Each entry represents a mixture; enter the desired tumor fractions (percent as a decimal) 
  TF0.13: 0.13
  TF0.14: 0.14
  TF0.15: 0.15
